[package]
name = "crc"
version = "1.6.0"
authors = ["Rui Hu <code@mrhooray.com>"]
description = "Rust implementation of CRC(32, 64) with support of various standards"
keywords = ["crc", "crc32", "crc64", "hash", "checksum"]
readme = "README.md"
repository = "https://github.com/mrhooray/crc-rs.git"
license = "MIT OR Apache-2.0"

[build-dependencies]
build_const = "0.2"

[features]
std = []
default = ["std"]
